ProbeTarget target
int32 frequency_threshold
float32 position_tolerance
float32 start_angle
float32 end_angle
int32 slices
float32 boundary_tol_z
float32 back_step_x
float32 back_step_z
float32 safety_margin
float32 safe_step
float32 probe_velocity
float32 init_z_offset
int32 pose_achieve_count
---
bool results
